### ISSUE TITLE
Github Changelog main issue

### ISSUE THREAD

**Issue by catalinmiron** [uberVU/github-changelog#1] opened 2014-05-15 12:24 UTC
## Need

``` gherkin
As a user
I want to be able to get notifications about new changes to an application
So that I can stay informed and be able to reload the application at my own will
```
## Deliverables

_inspiration from github on mac_
![inspiration from github on mac](https://dl.dropboxusercontent.com/u/42934143/images/QeNtYmshYw8u73fWTyyQH2-UmbOUtp9LazmMHWQqBPk.png)
- [ ] A jquery plugin which can check for updates on a GitHub project and notify the user by inserting and updating the notification list
- [ ] A HTML structure for the list
- [ ] A LESS / CSS library to provide styling for the list
#### Prerequisites
- [GitHub API](https://developer.github.com/v3/)
- [jQuery Plugins](http://learn.jquery.com/plugins/)
- [LESS](http://lesscss.org/)
#### Notes
1. Add default position to list, when no positioning classes are provided?
2. Notification button doesn't show up by default, only when there are notifications to be shown
3. All visual elements should have default styling but need to also be customizable. Right now this can be done via the variables in `variables.less`. Should we extend this further?
4. Reload button(see screenshot above). We need to discuss how to add a header that will contain the reload button and maybe a title. This can't be part of the ul, needs to be a separate element so that it doesn't scroll with the list.

cc: @uberVU/ux  @radvalentin

**Comment by ovidiuch** [comment] 2014-05-16 14:24
The main project specification should be in README.md. Anything that describes the behavior here and isn't already in the README should be added and this issue closed. If this is intended to aggregate all the smaller issues we have the [issues list](https://github.com/uberVU/github-changelog/issues) for that purpose :)

**Comment by RadValentin** [comment] 2014-05-16 14:36
Yes, it was intended to aggregate 3 main issues: plugin, html, less. Those in turn would branch out in other even smaller issues, that was the idea anyway. I think we can close this one and include the info in README.md

@catalinmiron what do you think?

**Comment by catalinmiron** [comment] 2014-05-16 14:48
@RadValentin you're right ! Doit :+1:

**Closed as completed** 2014-05-20 09:45 UTC
